### ISSUE TITLE
请教！

### ISSUE THREAD

**Issue by lmshens** [Liu1024/DDvoice#3]
您好，请问可以分享一下您写的语义识别吗？

**Comment by noobsolo** [comment]
用的讯飞语义识别库

**Comment by lmshens** [comment]
我在讯飞的官网里创建了项目，然后没有找到语义识别的内容啊，而且我下载语音听写的包里好像也缺东西

**Comment by noobsolo** [comment]
https://www.xfyun.cn/
产品 -> 语音扩展 -> 语义理解
你去看看哈，很多年了，改成啥样我也不太清楚了

**Comment by lmshens** [comment]
谢谢，我找到了，但是用不起来啊……不知道哪里有问题，能不能把您语义识别那部分的源码私发给我借鉴一下啊？邮箱：2877570091@qq.com

**Comment by lmshens** [comment]
谢谢，我找到了，但是用不起来啊……不知道哪里有问题，能不能把您语义识别那部分的源码私发给我借鉴一下啊？邮箱：2877570091@qq.com
